Support nested configurations
jcomellas/app_config pull request #1
Opened 2017-11-01 23:36 UTC by DrunkenInfant

Add support for nested configurations to allow fetching values in a hierarchical structure.

Adds support for Map.fetch in addition to Application.fetch_env and Keyword.fetch.

2017-11-16 14:13 UTC, jcomellas requested changes
Thanks for this feature. Sorry for the radio silence during 15 days, but the GitHub notification for this project got lost in the morass of notifications from other projects.

I left just a few minor comments. Also, could you please rebase before pushing the new changes?

2017-11-16 14:13 UTC, jcomellas commented on lib/app_config.ex
> +  def fetch_env(env, [ first_key | keys ]) when is_atom(env) or is_list(env) or is_map(env) do
@DrunkenInfant Could you keep the spacing in brackets and braces consistent with the rest of the code? In this case, the expression should be `[first_key | keys]`.

2017-11-16 14:13 UTC, jcomellas commented on lib/app_config.ex
> +  end
The `fetch_nested/2` function could be simplified a bit. Maybe to something like:
```elixir
defp fetch_nested(key, {:ok, val}) when is_map(val) or is_list(val) do
  fetch(val, key)
end
defp fetch_nested(_key, _result) do
  :error
end
```

2017-12-04 23:46 UTC, DrunkenInfant commented
Sorry for the delay. I fixed your comments.

2021-02-15 08:06 UTC, closed without merging